In [27]:
import numpy as np
import pandas as pd 
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', None)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings("ignore")

In [28]:
data = pd.read_csv("../SistersLab-Project/PCOS_data.csv")

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  541 non-null    int64
 1   Patient File No.        541 non-null    int64
 2   PCOS (Y/N)              541 non-null    int64
 3    Age (yrs)              541 non-null    int64
 4   Weight (Kg)             541 non-null    float64
 5   Height(Cm)              541 non-null    float64
 6   BMI                     541 non-null    float64
 7   Blood Group             541 non-null    int64
 8   Pulse rate(bpm)         541 non-null    int64
 9   RR (breaths/min)        541 non-null    int64
 10  Hb(g/dl)                541 non-null    float64
 11  Cycle(R/I)              541 non-null    int64
 12  Cycle length(days)      541 non-null    int64
 13  Marraige Status (Yrs)   540 non-null    float64
 14  Pregnant(Y/N)           541 non-null    int64
 15  No. of abortions        541 non-null    int64
 16    I   beta-HCG(mIU/mL)  541 non-null    float64
 17  II    beta-HCG(mIU/mL)  541 non-null    object
 18  FSH(mIU/mL)             541 non-null    float64
 19  LH(mIU/mL)              541 non-null    float64
 20  FSH/LH                  541 non-null    float64
 21  Hip(inch)               541 non-null    int64
 22  Waist(inch)             541 non-null    int64
 23  Waist:Hip Ratio         541 non-null    float64
 24  TSH (mIU/L)             541 non-null    float64
 25  AMH(ng/mL)              541 non-null    object
 26  PRL(ng/mL)              541 non-null    float64
 27  Vit D3 (ng/mL)          541 non-null    float64
 28  PRG(ng/mL)              541 non-null    float64
 29  RBS(mg/dl)              541 non-null    float64
 30  Weight gain(Y/N)        541 non-null    int64
 31  hair growth(Y/N)        541 non-null    int64
 32  Skin darkening (Y/N)    541 non-null    int64
 33  Hair loss(Y/N)          541 non-null    int64
 34  Pimples(Y/N)            541 non-null    int64
 35  Fast food (Y/N)         540 non-null    float64
 36  Reg.Exercise(Y/N)       541 non-null    int64
 37  BP _Systolic (mmHg)     541 non-null    int64
 38  BP _Diastolic (mmHg)    541 non-null    int64
 39  Follicle No. (L)        541 non-null    int64
 40  Follicle No. (R)        541 non-null    int64
 41  Avg. F size (L) (mm)    541 non-null    float64
 42  Avg. F size (R) (mm)    541 non-null    float64
 43  Endometrium (mm)        541 non-null    float64
 44  Unnamed: 44             2 non-null      object
dtypes: float64(19), int64(23), object(3)
memory usage: 190.3+ KB

In [30]:
data.sample(4)

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),Cycle length(days),Marraige Status (Yrs),Pregnant(Y/N),No. of abortions,I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),FSH(mIU/mL),LH(mIU/mL),FSH/LH,Hip(inch),Waist(inch),Waist:Hip Ratio,TSH (mIU/L),AMH(ng/mL),PRL(ng/mL),Vit D3 (ng/mL),PRG(ng/mL),RBS(mg/dl),Weight gain(Y/N),hair growth(Y/N),Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm),Unnamed: 44
369,370,370,0,35,60.0,152.0,26.0,15,74,18,10.0,2,5,3.0,1,0,116.31,116.31,6.52,3.42,1.91,39,36,0.92,0.77,2.5,40.73,20.000,0.30,92.0,1,0,0,1,0,1.0,0,110,80,3,4,12.0,15.0,8.0,NaN
498,499,499,0,23,52.0,148.0,23.7,15,72,20,11.0,2,5,4.0,0,0,1.99,1.99,7.72,4.10,1.88,32,30,0.94,5.00,5.1,12.60,25.900,0.50,92.0,0,0,0,0,0,0.0,0,120,80,1,1,7.0,17.0,6.0,NaN
47,48,48,0,26,40.0,156.0,16.4,13,74,18,10.2,2,5,3.0,1,0,1500.00,528.5,7.34,2.78,2.64,39,33,0.85,4.45,4.33,24.58,54.620,0.25,80.0,0,0,0,0,0,0.0,0,110,70,5,7,15.0,18.0,16.0,NaN
469,470,470,1,25,55.0,154.0,23.2,15,74,20,12.0,2,5,4.0,0,0,10.00,1.99,4.67,0.71,6.58,38,36,0.95,1.82,0.74,24.81,60.265,0.35,102.0,0,0,0,1,0,0.0,1,110,70,12,12,24.0,18.0,8.9,NaN

In [31]:
df = data.drop(["Sl. No", "Patient File No.",  "Unnamed: 44"], axis=1)

In [32]:
df.head()

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),Cycle length(days),Marraige Status (Yrs),Pregnant(Y/N),No. of abortions,I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),FSH(mIU/mL),LH(mIU/mL),FSH/LH,Hip(inch),Waist(inch),Waist:Hip Ratio,TSH (mIU/L),AMH(ng/mL),PRL(ng/mL),Vit D3 (ng/mL),PRG(ng/mL),RBS(mg/dl),Weight gain(Y/N),hair growth(Y/N),Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
0,0,28,44.6,152.0,19.3,15,78,22,10.48,2,5,7.0,0,0,1.99,1.99,7.95,3.68,2.16,36,30,0.83,0.68,2.07,45.16,17.1,0.57,92.0,0,0,0,0,0,1.0,0,110,80,3,3,18.0,18.0,8.5
1,0,36,65.0,161.5,24.9,15,74,20,11.70,2,5,11.0,1,0,60.80,1.99,6.73,1.09,6.17,38,32,0.84,3.16,1.53,20.09,61.3,0.97,92.0,0,0,0,0,0,0.0,0,120,70,3,5,15.0,14.0,3.7
2,1,33,68.8,165.0,25.3,11,72,18,11.80,2,5,10.0,1,0,494.08,494.08,5.54,0.88,6.30,40,36,0.90,2.54,6.63,10.52,49.7,0.36,84.0,0,0,0,1,1,1.0,0,120,80,13,15,18.0,20.0,10.0
3,0,37,65.0,148.0,29.7,13,72,20,12.00,2,5,4.0,0,0,1.99,1.99,8.06,2.36,3.42,42,36,0.86,16.41,1.22,36.90,33.4,0.36,76.0,0,0,0,0,0,0.0,0,120,70,2,2,15.0,14.0,7.5
4,0,25,52.0,161.0,20.1,11,72,18,10.00,2,5,1.0,1,0,801.45,801.45,3.98,0.90,4.42,37,30,0.81,3.57,2.26,30.09,43.8,0.38,84.0,0,0,0,1,0,0.0,0,120,80,3,4,16.0,14.0,7.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PCOS (Y/N)              541 non-null    int64
 1    Age (yrs)              541 non-null    int64
 2   Weight (Kg)             541 non-null    float64
 3   Height(Cm)              541 non-null    float64
 4   BMI                     541 non-null    float64
 5   Blood Group             541 non-null    int64
 6   Pulse rate(bpm)         541 non-null    int64
 7   RR (breaths/min)        541 non-null    int64
 8   Hb(g/dl)                541 non-null    float64
 9   Cycle(R/I)              541 non-null    int64
 10  Cycle length(days)      541 non-null    int64
 11  Marraige Status (Yrs)   540 non-null    float64
 12  Pregnant(Y/N)           541 non-null    int64
 13  No. of abortions        541 non-null    int64
 14    I   beta-HCG(mIU/mL)  541 non-null    float64
 15  II    beta-HCG(mIU/mL)  541 non-null    object
 16  FSH(mIU/mL)             541 non-null    float64
 17  LH(mIU/mL)              541 non-null    float64
 18  FSH/LH                  541 non-null    float64
 19  Hip(inch)               541 non-null    int64
 20  Waist(inch)             541 non-null    int64
 21  Waist:Hip Ratio         541 non-null    float64
 22  TSH (mIU/L)             541 non-null    float64
 23  AMH(ng/mL)              541 non-null    object
 24  PRL(ng/mL)              541 non-null    float64
 25  Vit D3 (ng/mL)          541 non-null    float64
 26  PRG(ng/mL)              541 non-null    float64
 27  RBS(mg/dl)              541 non-null    float64
 28  Weight gain(Y/N)        541 non-null    int64
 29  hair growth(Y/N)        541 non-null    int64
 30  Skin darkening (Y/N)    541 non-null    int64
 31  Hair loss(Y/N)          541 non-null    int64
 32  Pimples(Y/N)            541 non-null    int64
 33  Fast food (Y/N)         540 non-null    float64
 34  Reg.Exercise(Y/N)       541 non-null    int64
 35  BP _Systolic (mmHg)     541 non-null    int64
 36  BP _Diastolic (mmHg)    541 non-null    int64
 37  Follicle No. (L)        541 non-null    int64
 38  Follicle No. (R)        541 non-null    int64
 39  Avg. F size (L) (mm)    541 non-null    float64
 40  Avg. F size (R) (mm)    541 non-null    float64
 41  Endometrium (mm)        541 non-null    float64
dtypes: float64(19), int64(21), object(2)
memory usage: 177.6+ KB

In [34]:
df["PCOS (Y/N)"].value_counts()

PCOS (Y/N)
0    364
1    177
Name: count, dtype: int64

## Kolon isimlerinde düzenleme yaptım. Boşluklar rahatsız ediciydi.

In [35]:
df.rename(columns={'II    beta-HCG(mIU/mL)': 'II beta-HCG(mIU/mL)'}, inplace=True)
df.rename(columns={' Age (yrs)': 'Age (yrs)'}, inplace=True)
df.rename(columns={'  I   beta-HCG(mIU/mL)': 'I beta-HCG(mIU/mL)'}, inplace=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PCOS (Y/N)             541 non-null    int64
 1   Age (yrs)              541 non-null    int64
 2   Weight (Kg)            541 non-null    float64
 3   Height(Cm)             541 non-null    float64
 4   BMI                    541 non-null    float64
 5   Blood Group            541 non-null    int64
 6   Pulse rate(bpm)        541 non-null    int64
 7   RR (breaths/min)       541 non-null    int64
 8   Hb(g/dl)               541 non-null    float64
 9   Cycle(R/I)             541 non-null    int64
 10  Cycle length(days)     541 non-null    int64
 11  Marraige Status (Yrs)  540 non-null    float64
 12  Pregnant(Y/N)          541 non-null    int64
 13  No. of abortions       541 non-null    int64
 14  I beta-HCG(mIU/mL)     541 non-null    float64
 15  II beta-HCG(mIU/mL)    541 non-null    object
 16  FSH(mIU/mL)            541 non-null    float64
 17  LH(mIU/mL)             541 non-null    float64
 18  FSH/LH                 541 non-null    float64
 19  Hip(inch)              541 non-null    int64
 20  Waist(inch)            541 non-null    int64
 21  Waist:Hip Ratio        541 non-null    float64
 22  TSH (mIU/L)            541 non-null    float64
 23  AMH(ng/mL)             541 non-null    object
 24  PRL(ng/mL)             541 non-null    float64
 25  Vit D3 (ng/mL)         541 non-null    float64
 26  PRG(ng/mL)             541 non-null    float64
 27  RBS(mg/dl)             541 non-null    float64
 28  Weight gain(Y/N)       541 non-null    int64
 29  hair growth(Y/N)       541 non-null    int64
 30  Skin darkening (Y/N)   541 non-null    int64
 31  Hair loss(Y/N)         541 non-null    int64
 32  Pimples(Y/N)           541 non-null    int64
 33  Fast food (Y/N)        540 non-null    float64
 34  Reg.Exercise(Y/N)      541 non-null    int64
 35  BP _Systolic (mmHg)    541 non-null    int64
 36  BP _Diastolic (mmHg)   541 non-null    int64
 37  Follicle No. (L)       541 non-null    int64
 38  Follicle No. (R)       541 non-null    int64
 39  Avg. F size (L) (mm)   541 non-null    float64
 40  Avg. F size (R) (mm)   541 non-null    float64
 41  Endometrium (mm)       541 non-null    float64
dtypes: float64(19), int64(21), object(2)
memory usage: 177.6+ KB

## Normalde int/float olması gereken sütunların object olduğunu gördüm bunları sayısal değerlere çevirmek istedim.
* Burada '1.99.' şeklinde yazılmış str ifade olduğu için bunu ayrı düzenledim.

In [42]:
df[df["II beta-HCG(mIU/mL)"] == '1.99.']

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),Cycle length(days),Marraige Status (Yrs),Pregnant(Y/N),No. of abortions,I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),FSH(mIU/mL),LH(mIU/mL),FSH/LH,Hip(inch),Waist(inch),Waist:Hip Ratio,TSH (mIU/L),AMH(ng/mL),PRL(ng/mL),Vit D3 (ng/mL),PRG(ng/mL),RBS(mg/dl),Weight gain(Y/N),hair growth(Y/N),Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
123,1,23,40.0,150.0,17.8,15,74,18,10.8,2,5,2.0,0,0,1.99,1.99.,5.0,5.15,0.97,46,38,0.83,1.69,19.8,15.23,23.5,0.93,92.0,1,1,1,1,0,1.0,1,100,70,10,13,18.0,17.0,12.5

In [43]:
df.loc[df['II beta-HCG(mIU/mL)'] == '1.99.', 'II beta-HCG(mIU/mL)'] = 1.99

In [44]:
df[df["II beta-HCG(mIU/mL)"] == '1.99.'] # kontrol ettim tekrar

Empty DataFrame
Columns: [PCOS (Y/N), Age (yrs), Weight (Kg), Height(Cm) , BMI, Blood Group, Pulse rate(bpm) , RR (breaths/min), Hb(g/dl), Cycle(R/I), Cycle length(days), Marraige Status (Yrs), Pregnant(Y/N), No. of abortions, I beta-HCG(mIU/mL), II beta-HCG(mIU/mL), FSH(mIU/mL), LH(mIU/mL), FSH/LH, Hip(inch), Waist(inch), Waist:Hip Ratio, TSH (mIU/L), AMH(ng/mL), PRL(ng/mL), Vit D3 (ng/mL), PRG(ng/mL), RBS(mg/dl), Weight gain(Y/N), hair growth(Y/N), Skin darkening (Y/N), Hair loss(Y/N), Pimples(Y/N), Fast food (Y/N), Reg.Exercise(Y/N), BP _Systolic (mmHg), BP _Diastolic (mmHg), Follicle No. (L), Follicle No. (R), Avg. F size (L) (mm), Avg. F size (R) (mm), Endometrium (mm)]
Index: []

## Modeli çalıştırınca bir sütunda 'a' değeri olduğuna dair bir hata aldım. Bunun yerini tespit ettim.

In [45]:
df[df.index == 305]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),Cycle length(days),Marraige Status (Yrs),Pregnant(Y/N),No. of abortions,I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),FSH(mIU/mL),LH(mIU/mL),FSH/LH,Hip(inch),Waist(inch),Waist:Hip Ratio,TSH (mIU/L),AMH(ng/mL),PRL(ng/mL),Vit D3 (ng/mL),PRG(ng/mL),RBS(mg/dl),Weight gain(Y/N),hair growth(Y/N),Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
305,0,37,56.0,152.0,24.2,13,74,20,11.7,2,5,9.0,0,0,42.0,1.99,2.91,0.35,8.31,35,33,0.94,16.0,a,2.22,38.6,0.3,100.0,0,0,0,0,1,0.0,1,120,70,4,5,17.0,16.0,5.6

In [46]:
df.loc[df['AMH(ng/mL)'] == 'a', 'AMH(ng/mL)'] = np.nan # Bu değeri eksik değer olacak

In [47]:
df[df.index == 305] # kontrol ettim

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),Cycle length(days),Marraige Status (Yrs),Pregnant(Y/N),No. of abortions,I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),FSH(mIU/mL),LH(mIU/mL),FSH/LH,Hip(inch),Waist(inch),Waist:Hip Ratio,TSH (mIU/L),AMH(ng/mL),PRL(ng/mL),Vit D3 (ng/mL),PRG(ng/mL),RBS(mg/dl),Weight gain(Y/N),hair growth(Y/N),Skin darkening (Y/N),Hair loss(Y/N),Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
305,0,37,56.0,152.0,24.2,13,74,20,11.7,2,5,9.0,0,0,42.0,1.99,2.91,0.35,8.31,35,33,0.94,16.0,NaN,2.22,38.6,0.3,100.0,0,0,0,0,1,0.0,1,120,70,4,5,17.0,16.0,5.6

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PCOS (Y/N)             541 non-null    int64
 1   Age (yrs)              541 non-null    int64
 2   Weight (Kg)            541 non-null    float64
 3   Height(Cm)             541 non-null    float64
 4   BMI                    541 non-null    float64
 5   Blood Group            541 non-null    int64
 6   Pulse rate(bpm)        541 non-null    int64
 7   RR (breaths/min)       541 non-null    int64
 8   Hb(g/dl)               541 non-null    float64
 9   Cycle(R/I)             541 non-null    int64
 10  Cycle length(days)     541 non-null    int64
 11  Marraige Status (Yrs)  540 non-null    float64
 12  Pregnant(Y/N)          541 non-null    int64
 13  No. of abortions       541 non-null    int64
 14  I beta-HCG(mIU/mL)     541 non-null    float64
 15  II beta-HCG(mIU/mL)    541 non-null    object
 16  FSH(mIU/mL)            541 non-null    float64
 17  LH(mIU/mL)             541 non-null    float64
 18  FSH/LH                 541 non-null    float64
 19  Hip(inch)              541 non-null    int64
 20  Waist(inch)            541 non-null    int64
 21  Waist:Hip Ratio        541 non-null    float64
 22  TSH (mIU/L)            541 non-null    float64
 23  AMH(ng/mL)             540 non-null    object
 24  PRL(ng/mL)             541 non-null    float64
 25  Vit D3 (ng/mL)         541 non-null    float64
 26  PRG(ng/mL)             541 non-null    float64
 27  RBS(mg/dl)             541 non-null    float64
 28  Weight gain(Y/N)       541 non-null    int64
 29  hair growth(Y/N)       541 non-null    int64
 30  Skin darkening (Y/N)   541 non-null    int64
 31  Hair loss(Y/N)         541 non-null    int64
 32  Pimples(Y/N)           541 non-null    int64
 33  Fast food (Y/N)        540 non-null    float64
 34  Reg.Exercise(Y/N)      541 non-null    int64
 35  BP _Systolic (mmHg)    541 non-null    int64
 36  BP _Diastolic (mmHg)   541 non-null    int64
 37  Follicle No. (L)       541 non-null    int64
 38  Follicle No. (R)       541 non-null    int64
 39  Avg. F size (L) (mm)   541 non-null    float64
 40  Avg. F size (R) (mm)   541 non-null    float64
 41  Endometrium (mm)       541 non-null    float64
dtypes: float64(19), int64(21), object(2)
memory usage: 177.6+ KB

## gerekli düzenlemelerden sonra object>>float64 çevirmeleri yapıldı

In [49]:
df['II beta-HCG(mIU/mL)'] = pd.to_numeric(df['II beta-HCG(mIU/mL)'], errors='coerce').astype('float64')
df['AMH(ng/mL)'] = pd.to_numeric(df['AMH(ng/mL)'], errors='coerce').astype('float64')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PCOS (Y/N)             541 non-null    int64
 1   Age (yrs)              541 non-null    int64
 2   Weight (Kg)            541 non-null    float64
 3   Height(Cm)             541 non-null    float64
 4   BMI                    541 non-null    float64
 5   Blood Group            541 non-null    int64
 6   Pulse rate(bpm)        541 non-null    int64
 7   RR (breaths/min)       541 non-null    int64
 8   Hb(g/dl)               541 non-null    float64
 9   Cycle(R/I)             541 non-null    int64
 10  Cycle length(days)     541 non-null    int64
 11  Marraige Status (Yrs)  540 non-null    float64
 12  Pregnant(Y/N)          541 non-null    int64
 13  No. of abortions       541 non-null    int64
 14  I beta-HCG(mIU/mL)     541 non-null    float64
 15  II beta-HCG(mIU/mL)    541 non-null    float64
 16  FSH(mIU/mL)            541 non-null    float64
 17  LH(mIU/mL)             541 non-null    float64
 18  FSH/LH                 541 non-null    float64
 19  Hip(inch)              541 non-null    int64
 20  Waist(inch)            541 non-null    int64
 21  Waist:Hip Ratio        541 non-null    float64
 22  TSH (mIU/L)            541 non-null    float64
 23  AMH(ng/mL)             540 non-null    float64
 24  PRL(ng/mL)             541 non-null    float64
 25  Vit D3 (ng/mL)         541 non-null    float64
 26  PRG(ng/mL)             541 non-null    float64
 27  RBS(mg/dl)             541 non-null    float64
 28  Weight gain(Y/N)       541 non-null    int64
 29  hair growth(Y/N)       541 non-null    int64
 30  Skin darkening (Y/N)   541 non-null    int64
 31  Hair loss(Y/N)         541 non-null    int64
 32  Pimples(Y/N)           541 non-null    int64
 33  Fast food (Y/N)        540 non-null    float64
 34  Reg.Exercise(Y/N)      541 non-null    int64
 35  BP _Systolic (mmHg)    541 non-null    int64
 36  BP _Diastolic (mmHg)   541 non-null    int64
 37  Follicle No. (L)       541 non-null    int64
 38  Follicle No. (R)       541 non-null    int64
 39  Avg. F size (L) (mm)   541 non-null    float64
 40  Avg. F size (R) (mm)   541 non-null    float64
 41  Endometrium (mm)       541 non-null    float64
dtypes: float64(21), int64(21)
memory usage: 177.6 KB

In [51]:
y = df[["PCOS (Y/N)"]]
X = df.drop("PCOS (Y/N)", axis=1)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4, stratify=y)

In [53]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
accuracy_score(y_test,y_pred)

0.7889908256880734